apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkapp-argocd
spec:
  selector:
    matchLabels:
      app: mkapp
  replicas: 10
  template:
    metadata:
      labels:
        app: mkapp
  spec:
    containers:
    - name: mkapp
      image: nanjanshia/argocd-app:1.0
      ports:
      - containerPort: 8080