apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mockserver
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/richard.brockc/argocd-app-config.git
    targetRevision: HEAD
    path: mockserver
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
~                
